import type { AdminUser, LoginRecord, MotherProfile } from "@/lib/types";

export const mockAdmins: AdminUser[] = [
  {
    id: "admin-1",
    name: "Nadia Putri",
    email: "nadia@bundacare.id",
    role: "admin",
    qrToken: "ADM-NADIA-001",
    region: "Kelurahan Sukamaju",
  },
  {
    id: "admin-2",
    name: "Rizal Akbar",
    email: "rizal@bundacare.id",
    role: "admin",
    qrToken: "ADM-RIZAL-002",
    region: "Kelurahan Mekarjaya",
  },
  {
    id: "admin-3",
    name: "Dewi Lestari",
    email: "dewi@bundacare.id",
    role: "admin",
    qrToken: "ADM-DEWI-003",
    region: "Kelurahan Harapan Baru",
  },
];

export const mockLoginHistory: LoginRecord[] = [
  {
    id: "login-1",
    adminEmail: "nadia@bundacare.id",
    adminName: "Nadia Putri",
    method: "email",
    timestamp: "24 Apr 2026, 08:13",
    status: "success",
    device: "Chrome Windows",
  },
  {
    id: "login-2",
    adminEmail: "rizal@bundacare.id",
    adminName: "Rizal Akbar",
    method: "qr",
    timestamp: "24 Apr 2026, 07:48",
    status: "success",
    device: "Android Tablet",
  },
  {
    id: "login-3",
    adminEmail: "kader@wilayah.id",
    adminName: "Email tidak terdaftar",
    method: "email",
    timestamp: "23 Apr 2026, 19:22",
    status: "failed",
    device: "Safari iPhone",
  },
  {
    id: "login-4",
    adminEmail: "dewi@bundacare.id",
    adminName: "Dewi Lestari",
    method: "email",
    timestamp: "23 Apr 2026, 17:05",
    status: "success",
    device: "Edge Desktop",
  },
];

export const mockMothers: MotherProfile[] = [
  {
    id: "mother-1",
    qrCode: "BUNDA-001",
    fullName: "Siti Rahmawati",
    age: 27,
    category: "hamil",
    babyLossHistory: "tidak_ada",
    address: "Jl. Melati No. 8",
    village: "Kelurahan Sukamaju",
    rt: "03",
    rw: "05",
    latitude: -6.215,
    longitude: 106.8454,
    lastVisit: "22 Apr 2026",
    riskLevel: "rendah",
    notes: "Kehamilan 24 minggu, tekanan darah stabil, edukasi nutrisi sudah diberikan.",
    gestationalAgeWeeks: 24,
  },
  {
    id: "mother-2",
    qrCode: "BUNDA-002",
    fullName: "Nia Kurniasih",
    age: 31,
    category: "menyusui",
    babyLossHistory: "bayi_<1_tahun",
    address: "Perum Griya Sehat Blok C2",
    village: "Kelurahan Mekarjaya",
    rt: "07",
    rw: "03",
    latitude: -6.2274,
    longitude: 106.8321,
    lastVisit: "20 Apr 2026",
    riskLevel: "tinggi",
    notes: "Ibu menyusui eksklusif, perlu dukungan psikososial dan monitoring lanjutan.",
    childAgeMonths: 2,
  },
  {
    id: "mother-3",
    qrCode: "BUNDA-003",
    fullName: "Aisyah Hanum",
    age: 22,
    category: "hamil",
    babyLossHistory: "keguguran",
    address: "Jl. Kenanga Gang 2",
    village: "Kelurahan Harapan Baru",
    rt: "02",
    rw: "01",
    latitude: -6.2078,
    longitude: 106.8532,
    lastVisit: "21 Apr 2026",
    riskLevel: "tinggi",
    notes: "Riwayat keguguran 1 kali, butuh pengawasan ketat dan reminder kunjungan ANC.",
    gestationalAgeWeeks: 18,
  },
  {
    id: "mother-4",
    qrCode: "BUNDA-004",
    fullName: "Murni Sulastri",
    age: 29,
    category: "menyusui",
    babyLossHistory: "tidak_ada",
    address: "Jl. Flamboyan No. 14",
    village: "Kelurahan Sukamaju",
    rt: "05",
    rw: "05",
    latitude: -6.2124,
    longitude: 106.8612,
    lastVisit: "18 Apr 2026",
    riskLevel: "sedang",
    notes: "Produksi ASI cukup, bayi 4 bulan, jadwal imunisasi berikutnya perlu diingatkan.",
    childAgeMonths: 4,
  },
  {
    id: "mother-5",
    qrCode: "BUNDA-005",
    fullName: "Rina Marlina",
    age: 35,
    category: "hamil",
    babyLossHistory: "bayi_<3_bulan",
    address: "Kampung Sejahtera RT 09",
    village: "Kelurahan Mekarjaya",
    rt: "09",
    rw: "04",
    latitude: -6.2333,
    longitude: 106.8419,
    lastVisit: "24 Apr 2026",
    riskLevel: "tinggi",
    notes: "Usia ibu tinggi risiko, perlu home visit rutin dan koordinasi bidan wilayah.",
    gestationalAgeWeeks: 30,
  },
  {
    id: "mother-6",
    qrCode: "BUNDA-006",
    fullName: "Yuni Kartika",
    age: 26,
    category: "menyusui",
    babyLossHistory: "tidak_ada",
    address: "Jl. Dahlia No. 21",
    village: "Kelurahan Harapan Baru",
    rt: "04",
    rw: "02",
    latitude: -6.2014,
    longitude: 106.8376,
    lastVisit: "19 Apr 2026",
    riskLevel: "rendah",
    notes: "Pemantauan nifas baik, keluarga aktif mendukung pemberian ASI.",
    childAgeMonths: 6,
  },
];
